spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localove
    username: localove
    password: localove
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
#      TMP
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      localove.beta@gmail.com
    password:
      p4$$w0rd
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true

loca-love:
  jwt:
    secret: passssssssssssssssssssssswordddddddddddd
    expiration: 3h
  token:
    expiration: 2d

email:
  #Временно
  email-confirmation-url: http://example.org/
  password-restore-url: http://example.org/
  email-confirmation-template-file-path:
      /static/templates/emailConfirmationMessage
  password-restore-template-file-path:
      /static/templates/passwordRestoreMessage