spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localove
    username: localove
    password: localove
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
#      TMP
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

loca-love:
  jwt:
    secret: passssssssssssssssssssssswordddddddddddd
    expiration: 3h
  pictures:
    supported-types:
      - image/png
      - image/jpeg