spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LocaLove
    username: LocaLove
    password: LocaLove
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
#      TMP
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

loca-love:
  jwt:
    secret: passssssssssssssssssssssswordddddddddddd
    expiration: 3h